---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.4.4
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet5 PUPPET_GEM_VERSION="~> 5.0"
stages:
  - prepare cache
  - validate
  - build
  # - name: deploy
  #   if: branch = master1234
jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: validate
      env: CHECK=rubocop
    - stage: validate
      env: CHECK="syntax"
    - stage: validate
      env: CHECK="lint"
    - stage: validate
      env: CHECK=metadata_lint
    - stage: validate
      env: CHECK=spec
    - stage: validate
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=spec
    - stage: validate
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file"
# matrix:
#   fast_finish: true
#   include:
#     - stage: validate
#       env: CHECK=rubocop
#     - stage: validate
#       env: CHECK="syntax"
#     - stage: validate
#       env: CHECK="lint"
#     - stage: validate
#       env: CHECK=metadata_lint
#     - stage: validate
#       env: CHECK=spec
#     - stage: validate
#       env: PUPPET_GEM_VERSION="~> 5.0" CHECK=spec
#     - stage: validate
#       env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file"
#     - stage: build
#       dist: trusty
#       env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/centos-7
#       rvm: 2.4.4
#       script: bundle exec rake beaker
#       services: docker
#       sudo: required
#     - stage: build
#       dist: trusty
#       env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_PUPPET_COLLECTION=puppet5 BEAKER_set=docker/ubuntu-18.04
#       rvm: 2.4.4
#       script: bundle exec rake beaker
#       services: docker
#       sudo: required
# notifications:
#   email: false
# deploy:
#   provider: puppetforge
#   user: puppet
#   password:
#     secure: ""
#   on:
#     tags: true
#     all_branches: true
#     condition: "$DEPLOY_TO_FORGE = yes"
