---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.4.4
env:
  - PUPPET_GEM_VERSION="~> 5.0" CHECK=spec
stages:
  - validate
  - build
matrix:
  fast_finish: true
  include:
    - stage: validate
      env: CHECK=rubocop
    - stage: validate
      env: CHECK="syntax lint"
    - stage: validate
      env: CHECK=metadata_lint
    - stage: validate
      env: CHECK=spec
    - stage: validate
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=spec
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
